### ISSUE TITLE
consul like recursors?

### ISSUE THREAD

**Issue by nisbus** [dnsimple/erldns#108]
In consul you can specify recursors as upstream DNS resolvers.
is this possible with erldns (I couldn't see any reference to it in the code)?
if not, any plans for it?

**Comment by aeden** [comment]
Our current use for erldns is as the basis for an public-facing authoritative name server only, and at the moment we have no plans to implement support for providing resolver behavior, nor acting as a proxy to a resolver. Having said that, you could use erldns as an app inside an umbrella app and extend it, which is what we do for our authoritative implementation.

**Comment by nisbus** [comment]
thanks!
