### ISSUE TITLE
Remove support for delegating failed lookups

### ISSUE THREAD

**Issue by aeden** [dnsimple/erldns#121]
I am not sure if this functionality is in use, so I am proposing removing it the next major release, unless there is demand for it.

Furthermore, recent changes to the resolve logic for early returns when names are not present in the zone may have broken this functionality and I need to know if I need to set up a test and try to include the functionality in the recent updates.

https://github.com/dnsimple/erldns/pull/45 was the original PR for this functionality.

/cc @Licenser

**Comment by Licenser** [comment]
Thanks for asking! <3

The project I used it for still exists but isn't actively maintained anymore, so 👍 for removing it.

**Comment by aeden** [comment]
https://github.com/dnsimple/erldns/pull/123 will remove.

**Comment by aeden** [comment]
Done.
