### ISSUE TITLE
./rebar: not found

### ISSUE THREAD

**Issue by DemGiran** [dnsimple/erldns#81]
```
./build.sh: 4: ./build.sh: ./rebar: not found
./build.sh: 5: ./build.sh: ./rebar: not found
./build.sh: 6: ./build.sh: ./rebar: not found

```

Should I change this to rebar3 or is there something else I may be missing for the install process?

**Comment by aeden** [comment]
Go ahead and change it to `rebar3` for now. It may be better to just use `make` but I need to review and make sure the `build.sh` script is not used somewhere.
