### ISSUE TITLE
Warning related to discrepancy between RRSIG TTL and record TTL

### ISSUE THREAD

**Issue by weppos** [dnsimple/erldns#93]
Some domains are returning warnings as we use a TTL for the RRSIG record that doesn't match the TTL of the record itself.

![60517206-8e446d80-9cdf-11e9-842f-c6694149f680](https://user-images.githubusercontent.com/5387/60889813-32876080-a25a-11e9-8749-9322e8af94d4.png)

**Comment by aeden** [comment]
Fixed by 2f5830328535187e5f8200d81dba8885559cd56f
