### ISSUE TITLE
Adding multiple json zone files to the config

### ISSUE THREAD

**Issue by maxok** [dnsimple/erldns#96]
Hello,

We have installed erldns for testing purposes with around 100 zone json files. Is there any way we can indicate to include all *.zone.json files from priv directory as zones in erldns.config?

Best Regards,

Malkhaz

**Comment by aeden** [comment]
At the moment, no, only a single file can be loaded at a time. If you are interested in updating the code to support loading of multiple files, then https://github.com/dnsimple/erldns/blob/master/src/erldns_zone_loader.erl would need to be updated to support loading from a directory in addition to loading zones from a single JSON file.
